version: '3.8'

services:
  app:
    container_name: api-usuario
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_usuario
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db-apiusuario-postgres
    environment:
      POSTGRES_DB: db_usuario
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    ports:
      - "5431:5432"